import { createTheme } from '@shopify/restyle';

export const theme = createTheme({
  colors: {
    background: '#FFF9FB',
    surface: '#FFFFFF',
    surfaceMuted: '#F8F5F7',
    periodActual: '#E84572',
    periodAction: '#CF2F5D',
    periodPredicted: '#F8D4DE',
    symptom: '#7569A6',
    positive: '#3E927D',
    textPrimary: '#33282E',
    textSecondary: '#665A60',
    textMuted: '#766A70',
    border: '#EEE7EA',
    overlay: 'rgba(51, 40, 46, 0.28)',
    companionCanvas: '#FFF8FA',
    companionSurface: '#FFFCFD',
    companionCashmere: '#F6EEF1',
    companionCashmereStrong: '#E9DCE1',
    companionBerry: '#C02F5B',
    companionBerrySoft: '#F7C8D5',
    companionLavender: '#6D5C96',
    companionSage: '#4F7F72',
    companionInk: '#3A2E34',
    companionShadow: 'rgba(115, 77, 91, 0.16)',
    companionHighlight: 'rgba(255, 255, 255, 0.92)',
    transparent: 'transparent',
  },
  spacing: {
    none: 0,
    xs: 4,
    s: 8,
    m: 16,
    page: 20,
    l: 24,
    xl: 32,
    xxl: 40,
  },
  borderRadii: {
    none: 0,
    s: 4,
    m: 8,
  },
  textVariants: {
    defaults: {
      color: 'textPrimary',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0,
    },
    title: {
      color: 'textPrimary',
      fontSize: 26,
      fontWeight: '600',
      lineHeight: 34,
      letterSpacing: 0,
    },
    heroNumber: {
      color: 'textPrimary',
      fontSize: 42,
      fontWeight: '700',
      lineHeight: 50,
      fontVariant: ['tabular-nums'],
      letterSpacing: 0,
    },
    sectionTitle: {
      color: 'textPrimary',
      fontSize: 18,
      fontWeight: '600',
      lineHeight: 26,
      letterSpacing: 0,
    },
    body: {
      color: 'textPrimary',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0,
    },
    label: {
      color: 'textSecondary',
      fontSize: 15,
      fontWeight: '500',
      lineHeight: 22,
      letterSpacing: 0,
    },
    caption: {
      color: 'textMuted',
      fontSize: 13,
      lineHeight: 20,
      letterSpacing: 0,
    },
  },
});

export type AppTheme = typeof theme;
